### ISSUE TITLE
Error when requesting server

### ISSUE THREAD

**Issue by hadesss123** [google/cronet.dart#36]
When I use 32-bit dynamic library, whether it is http or quic, the following error occurs：

   [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Invalid argument(s): Count must be in the range [0, 1073741823].
    #0      _asExternalTypedData (dart:ffi-patch/ffi_patch.dart:45)
    #1      Uint8Pointer.asTypedList (dart:ffi-patch/ffi_patch.dart:432)
    #2      CallbackHandler.listen.<anonymous closure> (package:cronet/src/http_callback_handler.dart:170)
    #3      _rootRunUnary (dart:async/zone.dart:1444)
    #4      _CustomZone.runUnary (dart:async/zone.dart:1335)
    #5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244)
    #6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
    #7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
    #8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733)
    #9      _StreamController._add (dart:async/stream_controller.dart:607)
    #10     _StreamController.add (dart:async/stream_controller.dart:554)
    #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184)

**Comment by CensorKao** [comment]
@dcharkes Pls help.

**Comment by dcharkes** [comment]
Hey @CensorKao!

We need some more details to reproduce this issue.

What OS are you running on?
And what version of Dart are you using?
And can you please post a minimal reproduction?

**Comment by hadesss123** [comment]
I am using Cronet 0.0.7 on Android and Dart version is 2.14.4. @dcharkes

**Comment by dcharkes** [comment]
Just to clarify. So you're building for arm v7 32 bit.

1073741823 bytes in hex is `0x3FFFFFFF` which is an interesting number for the amount of bytes received. (I almost wouldn't be surprised if it would be 0xFFFFFFFF with the first two bits being chopped off.)

@unsuitable001 do you have a working Android setup? Could you take a look?
